### ISSUE TITLE
Shema

### ISSUE THREAD

**Issue by Alfourbe** [XylenC4/CO2-ESP32#1]
Hi,
thank you fo sharing, I plan to make it and I ordered MHz19 sensor, meanwhile there is a little error in the schema, MHZ and OLED GND line are not connected to ground.

How do you power it? via USB?

Thanks

**Comment by XylenC4** [comment]
Hey, yes USB power is good enough. I will check the "shematics" tomorrow. Thank you!

**Comment by XylenC4** [comment]
i fixed it and some other things! Thanks you for your remarks.

**Comment by JensTimmerman** [comment]
they still don't seem connected to ground but to 5v input?
