### ISSUE TITLE
No much info

### ISSUE THREAD

**Issue by ffnull** [XylenC4/CO2-ESP32#2]
Hello. Im buy all needed components and print housing. But you doesnt provide much info. Withch libraries  to use? And other

**Comment by XylenC4** [comment]
all of the used Arduino Libaries you can find on top of https://github.com/XylenC4/CO2-ESP32/blob/master/Arduino/CO2.ino


Adafruit_GFX
Adafruit_SSD1306
Adafruit_Sensor
Adafruit_Sensor

all the other are a part of the ESP32 Arduino enviroment.

**Comment by ffnull** [comment]
Cant compile. Warning on touchbutton. Witch version of arduino do you use?

**Comment by ffnull** [comment]
D:\Downloads\CO2-ESP32-master\CO2-ESP32-master\Arduino\CO2\Thingspeak.ino: In function 'void loop_Thingspeak()':

D:\Downloads\CO2-ESP32-master\CO2-ESP32-master\Arduino\CO2\Thingspeak.ino:14:23: warning: unused variable 'SensorLoop' [-Wunused-variable]

   static unsigned int SensorLoop = 0;

                       ^

D:\Downloads\CO2-ESP32-master\CO2-ESP32-master\Arduino\CO2\TouchButton.ino: In function 'int CheckMenuOrder()':

TouchButton:46:1: error: no return statement in function returning non-void [-Werror=return-type]

 }

 ^

cc1plus.exe: some warnings being treated as errors

exit status 1
no return statement in function returning non-void [-Werror=return-type]

**Comment by ffnull** [comment]
And. Please show the photo how you put everything inside.

**Comment by XylenC4** [comment]
Make shure you have https://dl.espressif.com/dl/package_esp32_index.json inside the preferences and install "esp32" v1.0.0 or v1.0.1 at the board manager. Then you have to select the board "DOIT ESP32 DEVKIT V1"

Please try to rename the folder "Arduino" to "CO2" (which is the original name for the project)

**Comment by XylenC4** [comment]
It's wired with 0.1 Header and soldered on the OLED & Touch Switches.
The sensors are glued with "hot snod".

https://github.com/XylenC4/CO2-ESP32/blob/master/Images/Wiring%201.jpg
https://github.com/XylenC4/CO2-ESP32/blob/master/Images/Wiring%202.jpg

**Comment by ffnull** [comment]
All done. But still cant compile. Full log https://pastebin.com/0xugvqDd

**Comment by XylenC4** [comment]
please update to Ardiono 1.8.8

**Comment by ffnull** [comment]
Change to 1.8.8. Still same error

**Comment by ffnull** [comment]
When i comment CheckMenuOrder function. Its compiles

**Comment by ffnull** [comment]
After flashing im got circle reboot with kernel panic

**Comment by ffnull** [comment]
Please add zip archive with your libraries

**Comment by XylenC4** [comment]
As requested: https://github.com/XylenC4/CO2-ESP32/tree/master/Arduino

**Comment by ffnull** [comment]
Strange. My board esp32 core board v2. Your code still give kernel panic.
`Guru Meditation Error: Core  1 panic'ed (IntegerDivideByZero). Exception was unhandled.`
What can be wrong?

**Comment by ffnull** [comment]
Any ideas?

**Comment by XylenC4** [comment]
Because of some other projects with bluetooth i flashed a newer firmware (which really helped) https://www.espressif.com/en/support/download/at

yours is "ESP32-WROVER" and can be flashed with https://github.com/espressif/esptool
On Windows you can use the esptool out of the Arduino Board Manager: %AppData%\..\Local\Arduino15\packages\esp32\tools\esptool_py\2.6.0

**Comment by ffnull** [comment]
Ok. Im update firmware from site. But have still same error

**Comment by ffnull** [comment]
Hah. My chip is esp-wroom-32. going to flash correct firmware

**Comment by ffnull** [comment]
Ok. Flash correct firmware. Then yours code. Still doesnt work

**Comment by XylenC4** [comment]
you can try to compile it on another computer where Arduino never was installed.
